### PR TITLE
feat: Adding a version of urlsigner.py for Python 3

### PR DESCRIPTION
**Pull request by nanotellez**
Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by nanotellez** [comment]
@googlebot I signed it!

**Review by jpoehnelt — CHANGES_REQUESTED** [review]
Can you make this `urlsigner.py` instead of having two versions?

**Comment by nanotellez** [comment]
I can, but I believe this new version is not compatible with Python 2.x.
That being said, Python 2 is officially no longer supported, so maybe
that's not such a bad thing. Let me know what you think.

--
Nano

**Comment by jpoehnelt** [comment]
For the case of python2, they can dig through git to find that version :) 🐍

**Comment by nanotellez** [comment]
@jpoehnelt  Done!

**Comment by nanotellez** [comment]
@googlebot I fixed it!

**Comment by jpoehnelt** [comment]
@nanotellez Need to sign it with the email in the git commit. nano@au****c.com

**Comment by nanotellez** [comment]
@jpoehnelt I noticed that as I was troubleshooting the issue. It's my work email, and I would prefer not to use it for this. I created a new pull request, with the right email instead. And we can close this one. I hope that's alright.

**Pull request closed without merging**
