### PR TITLE
Added Kotlin example for Android

### PR DESCRIPTION
**Pull request by FrankDev17**
Added Kotlin implementation to add Uri's extension in an Android Project, with dependencies over framework (android.util.*) for base 64 decoding and over javax.crypto.* for crypto

### CODE REVIEW

**Comment by FrankDev17** [comment]
I signed it!

**Comment by FrankDev17** [comment]
Could i know why is still in pending after 26 days? @domesticmouse

**Comment by domesticmouse** [comment]
Sorry for the delay, life got in the way. Thanks for the PR!

**Comment by prakhar241** [comment]
@fcorbi - I see you have used android Base64 - I wanted to use java Base64 package. Can you please explain your reason of using android package in Kotlin?
Can you share any test case to prove Kotlin code works correctly? 

I'm seeing incorrect signature key when I used this code and replaced java Base 64 package.
I've asked on stackoverflow as well -
https://stackoverflow.com/questions/60814118/need-help-in-kotlin-google-map-url-signer

**Pull request merged**
